# Generated by Django 4.2.4 on 2023-08-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0003_alter_alumno_certificado_analitico'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=400)),
                ('nota_director', models.FileField(upload_to='archivos/documentacion_trabajo/', verbose_name='Nota Director')),
                ('fecha_presentacion', models.DateField(blank=True, null=True, verbose_name='Fecha Presentacion')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_asesor', to='persona.asesor')),
                ('co_director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_co_irector', to='persona.docente')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_director', to='persona.docente')),
            ],
            options={
                'ordering': ('fecha_presentacion',),
            },
        ),
    ]
