# Generated by Django 4.2.4 on 2023-08-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajofinal',
            options={'ordering': ('fecha_presentacion',), 'verbose_name': 'Trabajo final', 'verbose_name_plural': 'Trabajos finales'},
        ),
    ]
