# Generated by Django 4.2.4 on 2023-08-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_alumno_certificado_analitico'),
        ('trabajo', '0002_alter_trabajofinal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('INIC', 'Proyecto Iniciado'), ('ENCS', 'Proyecto enviado CSTF')], default='INIC', max_length=4)),
                ('tiempo_maximo_dias', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_estados', to='trabajo.estado')),
                ('trabajo_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_movimientos', to='trabajo.trabajofinal')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta_alumno', models.DateField(blank=True, null=True, verbose_name='Fecha Alta')),
                ('fecha_baja_alumno', models.DateField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_integrante', to='persona.alumno')),
                ('trabajo_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_integrante', to='trabajo.trabajofinal')),
            ],
        ),
        migrations.CreateModel(
            name='DictamenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Dictamen')),
                ('tipo_dictamen', models.CharField(choices=[('PTF', 'Proyecto Trabajo Final'), ('BIF', 'Borrador Informe Final')], default='PTF', max_length=4)),
                ('resultado_tipo_dictamen', models.CharField(choices=[('A', 'Aprobado'), ('O', 'Observado'), ('D', 'Desaprobado')], default='A', max_length=1)),
                ('archivo', models.FileField(null=True, upload_to='archivos/documentacion_dictamen/', verbose_name='Archivo adjunto')),
                ('observaciones', models.TextField(blank=True)),
                ('trabajo_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_dictamenes', to='trabajo.trabajofinal')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Presentacion Archivo')),
                ('tipo_archivo', models.CharField(choices=[('PTF', 'Proyecto Trabajo Final'), ('BIF', 'Borrador Informe Final'), ('BIM', 'Borrador Informe Modificado')], default='PTF', max_length=3)),
                ('archivo', models.FileField(null=True, upload_to='archivos/documentacion_trabajo/', verbose_name='Archivo adjunto')),
                ('trabajo_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_archivos', to='trabajo.trabajofinal')),
            ],
        ),
        migrations.AddField(
            model_name='trabajofinal',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_finales_estados', to='trabajo.estado'),
            preserve_default=False,
        ),
    ]
