# Generated by Django 4.2.4 on 2023-08-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('apellido', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('apellido',),
            },
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('cuil', models.CharField(max_length=13)),
            ],
            bases=('persona.persona',),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('cuil', models.CharField(max_length=13)),
            ],
            bases=('persona.persona',),
        ),
    ]
